spring:
  application:
    name: thespace

  data:
    redis:
      host: localhost
      port: 6379
      password: "980414"

  servlet:
    multipart:
      enabled: true
      max-file-size: "100MB"
      max-request-size: "300MB"
      location: "C:/Users/CJM/OneDrive/DeskTop/thespace/files"

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: "true"
    show-sql: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: thespace
    password: webuser
    url: jdbc:mariadb://localhost:3307/thespace

  sql:
    init:
      mode: always

logging:
  level:
    com:
      thespace:
        thespace: trace
        springframework: trace


com:
  thespace:
    upload:
      path: "C:/Users/CJM/OneDrive/DeskTop/thespace/files"

server:
  servlet:
    session:
      timeout: 30m