= The Space API Docs
The Space API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[Borad-API]]
== Board API

[[Board-Post-API]]
=== Post-API
operation::board-controller-test/board-post[snippets='http-request,http-response']

return value = Board Number (bno)

operation::board-controller-test/board-post[snippets='request-fields']

=== Read-API
operation::board-controller-test/board-read[snippets='http-request,http-response,path-parameters,response-fields']

=== List-API
operation::board-controller-test/board-list[snippets='http-request,request-fields,response-fields']

=== Modify-API
operation::board-controller-test/board-modify[snippets='http-request,http-response,request-fields']

=== Delete-API
operation::board-controller-test/board-delete[snippets='http-request,http-response,path-parameters,form-parameters']

=== Delete with Admin-API
operation::board-controller-test/board-admin-delete[snippets='http-request,http-response,path-parameters,form-parameters']
