= The Space API Docs
The Space API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[Borad-API]]
== Board API

=== Post-API
    Required Authentication 

operation::board-controller-test/board-post[snippets='curl-request,http-response']
|===
 |field|Description
 |return value|Board Number (bno)
|===

operation::board-controller-test/board-post[snippets='request-fields']

=== Read-API
operation::board-controller-test/board-read[snippets='curl-request,path-parameters,http-response,response-fields']

=== List-API
operation::board-controller-test/board-list[snippets='curl-request,query-parameters,response-fields']

=== Modify-API
    Required Authentication 

operation::board-controller-test/board-modify[snippets='curl-request,request-fields,http-response']

=== Delete-API
    Required Authentication 

operation::board-controller-test/board-delete[snippets='curl-request,path-parameters,http-response']

=== Delete with Admin-API
    Required Authentication 

operation::board-controller-test/board-admin-delete[snippets='curl-request,path-parameters,query-parameters,http-response']

[[Category-API]]
== Category API

=== List-API
operation::category-controller-test/category-list[snippets='curl-request,query-parameters,response-fields']

=== Create with Admin-API
    Required Authentication 

operation::category-controller-test/category-create[snippets='curl-request,request-fields,http-response']

=== Delete with Admin-API
    Required Authentication 

operation::category-controller-test/category-delete[snippets='curl-request,path-parameters,query-parameters,http-response']

[[Community-API]]
== Community API

=== Get-API
operation::community-controller-test/community-get[snippets='curl-request,path-parameters,http-response,response-fields']

=== List-API
operation::community-controller-test/community-list[snippets='curl-request,query-parameters,response-fields']

=== Create-API
    Required Authentication 

operation::community-controller-test/community-create[snippets='curl-request,request-fields,query-parameters,http-response']

=== Check-API
operation::community-controller-test/community-check[snippets='curl-request,query-parameters,http-response']

=== Delete-API
    Required Authentication 

operation::community-controller-test/community-delete[snippets='curl-request,path-parameters,query-parameters,http-response']

=== AdminGetList-API
    Required Authentication 

operation::community-controller-test/community-has-admin-list[snippets='curl-request,http-response,response-fields']

=== Modify-API
    Required Authentication 

operation::community-controller-test/community-modify[snippets='curl-request,request-fields,http-response']

[[File-API]]
== File API

=== Upload-API
operation::file-controller-test/file-upload[snippets='curl-request,request-parts,http-response,response-fields']

=== Get-API
operation::file-controller-test/file-get[snippets='curl-request,path-parameters,http-response']

=== Delete-API
operation::file-controller-test/file-delete[snippets='curl-request,path-parameters,http-response']

[[Reply-API]]
== Reply API

=== Register-APi
    Required Authentication 

operation::reply-controller-test/reply-register[snippets='curl-request,path-parameters,request-fields,http-response']

=== List-API
operation::reply-controller-test/reply-list[snippets='curl-request,path-parameters,http-response,response-fields']

=== NestedList-API
operation::reply-controller-test/reply-nested-list-get[snippets='curl-request,path-parameters,http-response,response-fields']

=== Delete-API
    Required Authentication 

operation::reply-controller-test/reply-delete[snippets='curl-request,path-parameters,http-response']

[[Like-API]]
== Like API

=== Like-API
    Required Authentication 

operation::like-controller-test/like-like[snippets='curl-request,request-fields,http-response']
|===
    |Field|Type|Description
    |Body|int| If performer has no history of like to target post or reply, 1. +
But, if performer has a history, -1.
|===

[[User-API]]
== User API

=== Register-API
operation::user-controller-test/user-register[snippets='curl-request,request-fields,http-response']

=== Check-API
operation::user-controller-test/user-check[snippets='curl-request,query-parameters,http-response']
|===
    |Field|Type|Description
    |Body|boolean|If that ID already exists, false, otherwise true.
|===

=== GetUserInfo-API
    Required Authentication 

operation::user-controller-test/user-get-user-info[snippets='curl-request']

operation::user-controller-test/user-get-user-info[snippets='http-response,response-fields']